import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from "@mantine/core";
import "./globals.css";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "ABUY.com",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" {...mantineHtmlProps}>
        <head>
          <ColorSchemeScript />
        </head>
        <body className={`${inter.className} antialiased flex flex-col overflow-x-hidden`}>
          <MantineProvider>
            <Header />
            {children}
            <Footer />
          </MantineProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
